name: DeepCircle
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=1.0.0
  - aiohttp=3.7.4.post0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.4.0
  - beautifulsoup4=4.10.0
  - bedtools=2.30.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.11
  - click=8.0.1
  - colorama=0.4.4
  - cryptography=35.0.0
  - dataclasses=0.8
  - filelock=3.0.4
  - gast=0.3.3
  - gdown=4.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.38.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=3.3
  - idna_ssl=1.1.0
  - importlib-metadata=4.8.1
  - joblib=1.1.0
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libgpuarray=0.7.6
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libprotobuf=3.18.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - mako=1.1.6
  - markdown=3.3.6
  - markupsafe=2.0.1
  - multidict=5.2.0
  - ncurses=6.3
  - numpy=1.19.5
  - oauthlib=3.2.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - pandas=1.1.5
  - pip=21.3.1
  - protobuf=3.18.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygpu=0.7.6
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=5.4.1
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=0.24.2
  - scipy=1.5.3
  - setuptools=58.0.4
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.37.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - theano=1.0.3
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - toolchain=2.4.0
  - toolchain_c_linux-64=2.4.0
  - toolchain_cxx_linux-64=2.4.0
  - tqdm=4.62.3
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - urllib3=1.26.8
  - werkzeug=2.0.2
  - wheel=0.37.1
  - wrapt=1.13.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.6.0
  - zlib=1.2.11
